### ISSUE TITLE
[FYI] Problem with Numba 0.42, likely solved in 0.43

### ISSUE THREAD

**Issue by luk-f-a** [QuantEcon/rvlib#15]
Hi, thanks for sharing this very useful library. I'd like to report that there's an issue with numba 0.42 (0.41 is fine). While I was preparing this bug report I checked against the latest numba master (which I assume contains fixes to be included in the future 0.43) and the problem went away.

I'll leave this githut issue in case someone has the same problem and comes looking for a solution.

Reproducing example
```python
from numba import njit
import rvlib as rl


@njit
def myfun(x):
    N_dist = rl.Normal(0, 1)
    rho_t = N_dist.pdf(x)
    return rho_t

myfun(0.1)
```

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lucio/anaconda3/envs/rvlib/lib/python3.6/site-packages/numba/dispatcher.py", line 348, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/lucio/anaconda3/envs/rvlib/lib/python3.6/site-packages/numba/dispatcher.py", line 315, in error_rewrite
    reraise(type(e), e, None)
  File "/home/lucio/anaconda3/envs/rvlib/lib/python3.6/site-packages/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'rl': cannot determine Numba type of <class 'numba.ir.UndefinedType'>

File "<stdin>", line 3:
<source missing, REPL/exec in use?>

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.
```

**Comment by knaaptime** [comment]
i think this is no longer an issue, but feel free to reopen if it reoccurs
